### ISSUE TITLE
Arduinojson V6.7.0 library

### ISSUE THREAD

**Issue by mbta009** [ayushsharma82/ESP-DASH#14]
Thanks for amazing Dash. 
for test and compile new Lib ESP-Dash V2 , problem working with Arduino json V6.7.0 .
Search and test 10 hour but can't do that. some error in detail: 
"DynamicJsonDocument' was not declared in this scope"
'doc' was not declared in this scope
'deserializeJson' was not declared in this scope
expected primary-expression before '>' token
...
Is it possible to share the library with the tested project? Thanks
I'm sorry for the weak English.

**Comment by ayushsharma82** [comment]
@mbta009  That happens when using ArduinoJson version 5..  I just compiled my examples successfully.

Can you please verify again in 'Arduino Library Manager' that ArduinoJson v6.7.0 is installed?

**Comment by mbta009** [comment]
yes, your idea tested, that worked for me.Delete V5 and just install ArduinoJson v6.7.0 and use that. 
Thanks.
